### PR TITLE
otp version  bump: 19.3

### PR DESCRIPTION
**Pull request by tsloughter**

### CODE REVIEW

**Comment by c0b** [comment]
looks good if ignoring whitespace: https://github.com/c0b/docker-erlang-otp/pull/39/files?w=1 but is there any particular reason you want to change all tabs to spaces?

**Comment by tsloughter** [comment]
Oh, woops, no, that must just be my emacs dockerfile mode :(. I guess I can tell git to skip the whitespace changes.

**Comment by tsloughter** [comment]
Fixed.

**Comment by c0b** [comment]
good to merge; please also make a PR for `docker-library/official-images` to merge, follow the pattern of

https://github.com/docker-library/official-images/pulls?q=label:library/erlang

**Pull request merged**
