### PR TITLE
add support for wxwidget app; and dirty scheduler

### LINKED ISSUE #28: include tk graphical libraries for observer
the original goal for this repo was to deliver an Erlang container as close as possible to upstream (https://github.com/erlang/otp/releases) within reasonable image size, it turns out to be the current approach: download source code tarball from upstream, and compile it during building the docker image, this way we can control 3rd party library dependencies as minimum and most often used ones; so that it didn't pull in all java for jinterface, and gtk/gl for wxwidgets (which is a required dependency for observer to start, see observer source code at https://github.com/erlang/otp/tree/maint/lib/observer/src, it is a wxwidgets application.)

Now @AugustoPedraza is requesting to use observer (see c0b/docker-elixir#19 for background), it is totally possible to include gtk/gl for wxwidgets during the compiling; the only question is should we do it? or maintain another variant?

@sdwolf gives another example of using the precompiled packages from erlang-solutions: https://github.com/c0b/docker-elixir/issues/19#issuecomment-257648388
I was aware of this approach but didn't choose it since the beginning of this project was because they were not releasing as often as today, there was some lags behind erlang upstream, but now in 2016 it seems ok, from erlang-solutions we can get pretty latest once every upstream release, we can have a image size test and it's probably ok to switch

The other approach was to use OS/Distro pre-packages many Linux distros were packaging Erlang very trivial https://packages.debian.org/jessie/erlang and not preferred,
https://packages.debian.org/sid/erlang https://packages.debian.org/jessie-backports/erlang

Please vote here what changes you want to see in the Erlang base image.

### PR DESCRIPTION
**Pull request by c0b**
fixes #28 #29

```
REPOSITORY     TAG                   IMAGE ID            CREATED             SIZE    
otp            19.1-wx               baed4487102d        6 minutes ago       815.6 MB
otp            20.0-rc0-a373987-wx   5cfda149e228        About an hour ago   814.9 MB
```

### CODE REVIEW

**Comment by c0b** [comment]
@radupopescu you may check this out and build locally for some test; or just wait some more feedback from others before merge into official-images

**Comment by radupopescu** [comment]
@c0b I'll try to build the images locally when I'm at work. Thanks!

**Comment by c0b** [comment]
closes for #34

**Comment by radupopescu** [comment]
Thanks!

Sorry, for the late reply. I just finished building the test image (I had Docker issues re: DNS masq on Ubuntu). As far as I can tell, all is ok.

**Pull request merged**
