### PR TITLE
Update rebar/rebar3 to latest version

### PR DESCRIPTION
**Pull request by zyegfryed**

### CODE REVIEW

**Comment by c0b** [comment]
please have a look at CI build failure log, could you update the SHA256SUM as well?

https://travis-ci.org/c0b/docker-erlang-otp/jobs/156210183#L8068

**Comment by zyegfryed** [comment]
My bad... Done!
PS: I rebased the commit to have only one. I find it much cleaner. YMMV

**Comment by c0b** [comment]
it's interesting that when I want to test this today, just found rebar released 2.6.4 a few hours ago, do you want to update to that instead? we can skip 2.6.3
https://github.com/rebar/rebar/releases

**Comment by zyegfryed** [comment]
Ahah. No problem I'm doing it.

**Comment by zyegfryed** [comment]
Done ;)

**Comment by c0b** [comment]
I have built it locally and it runs look like fine; so I merged it, while the image at http://hub.docker.com/_/erlang/ is still the old one because that's managed by the official-images; if you like you can make a PR to there (examples: https://github.com/docker-library/official-images/issues?q=label:library/erlang ) or I think it's good to be staged for next erlang releases

```console
root@98c790ea9877:/# rebar version
rebar 2.6.4 20 20160901_221634 No VCS info available.
root@98c790ea9877:/# rebar3 version
rebar 3.3.0 on Erlang/OTP 20 Erts 8.0.3
```

**Comment by zyegfryed** [comment]
Yeah, it's OK for the next erlang release. Thanks!

**Pull request merged**
