### PR TITLE
add crypto / ssl into alpine; image size 34MB

### PR DESCRIPTION
**Pull request by c0b**
in EXTRA_APPLICATIONS:

- for ssl: crypto public_key asn1 ssl
- for exlixir: erl_interface syntax_tools
- for rebar3: eunit dialyzer edoc snmp

also keep include/*.hrl files to be able to build more applications.

I have pushed my own build to this repo if you like to try

https://hub.docker.com/r/c0b0/otp/tags/

Tag Name | Compressed Size | Last Updated
---|----|----
21.0-rc0-50525f3 | 328 MB | 22 minutes ago
21.0-rc0-50525f3-alpine | 21 MB | 23 minutes ago
20.0.1-alpine | 21 MB | 2 days ago

### CODE REVIEW

**Comment by c0b** [comment]
```console
$ docker run -ti --rm c0b0/otp:21.0-rc0-50525f3-alpine erl -s inets -s ssl
Erlang/OTP 21 [DEVELOPMENT] [erts-9.0.1] [source-50525f3] [64-bit] [smp:24:24] [ds:24:24:10] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V9.0.1  (abort with ^G)
1> application:loaded_applications().
[{public_key,"Public key infrastructure","1.4.1"},
 {stdlib,"ERTS  CXC 138 10","3.4.1"},
 {crypto,"CRYPTO","4.0"},
 {inets,"INETS  CXC 138 49","6.4"},
 {ssl,"Erlang/OTP SSL application","8.2"},
 {kernel,"ERTS  CXC 138 10","5.3"},
 {asn1,"The Erlang ASN1 compiler version 5.0","5.0"}]
2> httpc:request("https://raw.githubusercontent.com/erlang/otp/master/OTP_VERSION").
{ok,{{"HTTP/1.1",200,"OK"},
     [{"cache-control","max-age=300"},
      {"connection","keep-alive"},
      {"date","Fri, 14 Jul 2017 02:25:20 GMT"},
      {"via","1.1 varnish"},
      {"accept-ranges","bytes"},
      {"etag","\"06d4ac2bfde6016e29e83b6c009c09c347f27d8d\""},
      {"vary","Authorization,Accept-Encoding"},
      {"content-length","9"},
      {"content-type","text/plain; charset=utf-8"},
      {"expires","Fri, 14 Jul 2017 02:30:20 GMT"},
      {"content-security-policy",
       "default-src 'none'; style-src 'unsafe-inline'"},
      {"strict-transport-security","max-age=31536000"},
      {"x-content-type-options","nosniff"},
      {"x-frame-options","deny"},
      {"x-xss-protection","1; mode=block"},
      {"x-geo-block-list",[]},
      {"x-github-request-id","96C2:228F8:C4EEA:D4B81:59682B90"},
      {"x-served-by","cache-lax8646-LAX"},
      {"x-cache","MISS"},
      {"x-cache-hits","0"},
      {"x-timer","S1499999120.330855,VS0,VE51"},
      {"access-control-allow-origin","*"},
      {"x-fastly-request-id",[...]},
      {[...],...}],
     "21.0-rc0\n"}}
3> 
User switch command
 --> q
```

**Comment by mathewdgardner** [comment]
@c0b This works until you have an elixir app that needs another erlang app like exmerl -> xmerl. I wonder if we can remove the `OTP_SMALL_BUILD=true` or is there another way to go about it?

**Comment by c0b** [comment]
yes, I agree that we should remove `OTP_SMALL_BUILD=true`, to keep the alpine image to be below 30MB is unrealistic,

I have tested with erlang 20.0.1; remove `OTP_SMALL_BUILD=true` will result an image at 58.14 MB, not too bad? it has these 35 erlang apps:

```console
/ # ls /usr/local/lib/erlang/lib/
asn1-5.0               edoc-0.9               mnesia-4.15
compiler-7.1           eldap-1.2.2            observer-2.4
cosEvent-2.2.1         erl_docgen-0.7         os_mon-2.4.2
cosEventDomain-1.2.1   erl_interface-3.10     otp_mibs-1.1.1
cosFileTransfer-1.2.1  erts-9.0.1             public_key-1.4.1
cosNotification-1.2.2  et-1.6                 reltool-0.7.4
cosProperty-1.2.2      eunit-2.3.3            sasl-3.0.4
cosTime-1.2.2          hipe-3.16              snmp-5.2.6
cosTransactions-1.3.2  ic-4.4.2               stdlib-3.4.1
debugger-4.2.2         inets-6.4              wx-1.8.1
dialyzer-3.2           kernel-5.3             xmerl-1.3.15
diameter-2.0           megaco-3.18.2
/ # ls /usr/local/lib/erlang/lib/ | wc -l
35
```

**Comment by c0b** [comment]
add openssl-dev (for crypto and ssl) to build should be 43 apps

```console
/ # ls /usr/local/lib/erlang/lib/
asn1-5.0               eldap-1.2.2            parsetools-2.1.5
common_test-1.15.1     erl_docgen-0.7         public_key-1.4.1
compiler-7.1           erl_interface-3.10     reltool-0.7.4
cosEvent-2.2.1         erts-9.0.1             runtime_tools-1.12.1
cosEventDomain-1.2.1   et-1.6                 sasl-3.0.4
cosFileTransfer-1.2.1  eunit-2.3.3            snmp-5.2.6
cosNotification-1.2.2  hipe-3.16              ssh-4.5
cosProperty-1.2.2      ic-4.4.2               ssl-8.2
cosTime-1.2.2          inets-6.4              stdlib-3.4.1
cosTransactions-1.3.2  kernel-5.3             syntax_tools-2.1.2
crypto-4.0             megaco-3.18.2          tools-2.10.1
debugger-4.2.2         mnesia-4.15            wx-1.8.1
dialyzer-3.2           observer-2.4           xmerl-1.3.15
diameter-2.0           os_mon-2.4.2
edoc-0.9               otp_mibs-1.1.1
/ # ls /usr/local/lib/erlang/lib/ | wc -l
43
```

**Pull request closed without merging**
